alz_unique_found_groups = ['C(=O)O', 'CN', 'CO']
hiv_unique_found_groups = ['COC', 'c1ccccc1', 'C(=O)O', 'CN', 'CO']
dementia_unique_found_groups = ['C(=O)O', 'CN', 'CO']
diabetes_unique_found_groups = ['CS', 'CSC', 'c1ccccc1', 'C(=O)O', 'CN', 'CO']
depression_unique_found_groups = ['c1ccccc1', 'CN', 'COC', 'CO']
anxiety_unique_found_groups = ['c1ccccc1', 'CN', 'CO']
hemerrhoids_unique_found_groups = ['CN', 'CC(=O)C', 'CO']
yeast_infection_unique_found_groups = ['c1ccccc1', 'CN', 'COC', 'CO']
lupus_unique_found_groups = ['CN', 'CCl', 'C(=O)O', 'CC(=O)C', 'CO']
shingles_unique_found_groups = ['C(=O)O', 'CC(=O)OC', 'COC', 'CO']
psoriasis_unique_found_groups = ['CS', 'CO']
bronchitis_unique_found_groups = ['C(=O)O', 'CN', 'CO']
pneumonia_unique_found_groups = ['C(=O)O', 'CN', 'CO']
strep_unique_found_groups = ['C(=O)O', 'CN', 'CO']
flu_unique_found_groups = ['C(=O)O', 'CN', 'CO']
hbp_unique_found_groups = ['C(=O)O', 'CN', 'CO']
cancer_unique_found_groups = ['C(=O)O', 'CN', 'CO']
diarrhea_unique_found_groups = ['C(=O)O', 'CN', 'CO']
covid_unique_found_groups = ['C(=O)O', 'CN', 'CO']
arthritis_unique_found_groups = ['C(=O)O', 'CN', 'CO']
